name: doctor_appointment
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  lottie: ^3.1.0
  provider: ^6.1.2
  rating_dialog: ^2.0.4
  shared_preferences: ^2.2.3
  table_calendar: ^3.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
